
import FWCore.ParameterSet.Config as cms

def getRA2PATOutput(process):
  from PhysicsTools.Configuration.SUSY_pattuple_cff import getSUSY_pattuple_outputCommands
  RA2PATOutput = cms.untracked.vstring('drop *', *getSUSY_pattuple_outputCommands( process ))
  RA2PATOutput.extend([
    'keep edmMergeableCounter_*Counter_*_*',
    'keep *_generalTracks_*_RECO',
    'keep recoPFRecHits_particleFlow*_Cleaned_*',
    'keep recoPFCandidates_particleFlow_*_*',
    'keep recoMuons_muons_*_*',
    'keep recoGsfTracks_electronGsfTracks_*_*',
    'keep recoGsfElectrons_gsfElectrons_*_*',
    'drop recoElectronSeeds_*_*_*',
    'keep *_gsfElectronCores_*_*',
    'keep *_photons_*_*', ##added for redoing isolations later
    'keep *_photonCore_*_*',
    'keep recoConversions_conversions_*_*',
    'drop recoTracks_*onversions_*_*',
    'keep *_reducedEcalRecHits*_*_*',
    'drop *_badEcalRecHits_*_*',
    'drop *_badHcalRecHits_*_*',
    'keep *_badTowers_*_*',
    'keep *_badMET_*_*',
    'keep *_badPFMET_*_*',
    'drop *_kt*_*_*',
    'drop *_ak7*_*_*',
    'drop *_iterativeCone5*_*_*',
    'drop recoTrackJets_ak5TrackJets__*',
    'drop recoRecoChargedRefCandidates_trackRefsForJets__*',
    'drop patMHTs_*_*_*',
    'keep HcalNoiseSummary_*_*_*',
    'drop edmTriggerResults_TriggerResults__*',
    'keep edmTriggerResults_TriggerResults__HLT',
    'keep edmTriggerResults_TriggerResults__REDIGI*',
    #'keep *_patPhotons_*_*',  ##removed since the patPhotonsRA2 are the same collection with the isolations added in
    'drop *_cleanPatPhotons_*_*',
    'keep *_patPhotonsRA2_*_*',
    'keep *_patElectrons*_*_*',
    'keep *_patMuons*_*_*',
    'keep *_muonPFCandidateProducer_*_*',
    'drop *_patTaus_*_*',
    'keep recoPFMETs_pfMet__*',
    'keep *_patMETs*_*_*',
    'keep *_patJetsAK5*_*_*',
    'keep *_patJetsPF_*_*',
    #'keep *_patJetsIC5*_*_*',
    'drop *_patJetsIC5*_*_*',
    'drop recoBaseTagInfosOwned_*_tagInfos_*',
    'drop CaloTowers_*_caloTowers_*',
    'drop recoPFCandidates_*_pfCandidates_*',
    'keep recoPFCandidates_patJetsPF_pfCandidates_*',
    'keep recoPFCandidates_patJetsAK5PF_pfCandidates_*',
    'drop recoGenJets_*_genJets_*',
    'drop recoVertexs_offlinePrimaryVerticesWithBS_*_*',
    'keep recoVertexs_goodVertices_*_*',
    'keep recoVertexs_goodVerticesRA2_*_*',
    'keep *_*htCalo_*_*',
    'keep *_*htPF_*_*',
    'keep *_*htPFchs_*_*',
    'keep *_maskedECALProducer_*_*',
    'keep *_ecalTPSkim_*_*',
    'keep recoTracks_globalMuons_*_*',
    'keep recoTracks_standAloneMuons_*_*',
    'keep *_ecalAnomalousFilter_*_*',
    'keep *_addPileupInfo_*_*',
    'keep triggerTriggerEvent_hltTriggerSummaryAOD_*_HLT',
    'keep *_HBHENoiseFilterRA2_*_*',
    'keep *_beamHaloFilter_*_*',
    'keep *_eeNoiseFilter_*_*',
    'keep *_trackingFailureFilter_*_*',
    'keep *_inconsistentMuons_*_*',
    'keep *_greedyMuons_*_*',
    'keep *_ra2EcalTPFilter_*_*',
    'keep *_ra2EcalBEFilter_*_*',
    'keep *_hcalLaserEventFilter_*_*',
    'keep *_ecalLaserCorrFilter_*_*',
    'keep *_eeBadScFilter_*_*',
    'keep *_manystripclus53X_*_*',
    'keep *_toomanystripclus53X_*_*',
    'keep *_logErrorTooManyClusters_*_*',
    'keep *_ak5PFJets_rho_*',
    'keep *_ak5PFJets_sigma_*',
    'keep *_kt6PFJets*_rho_*',
    'keep *_kt6PFJets*_sigma_*',
    'keep LHEEventProduct_*_*_*',
    'keep LHERunInfoProduct_*_*_*',
    'keep *_puJetIdChs_*_*',
    'keep *_puJetMvaChs_*_*',
    'keep recoPFCandidates_pfNoPileUpIso*_*_*',
    'keep *_kt6PF*_*_*',
    'keep *_*PFIsoDeposit*_*_*',
    'keep *_elPFIsoValueCharged03PFIdPFIso_*_*',
    'keep *_elPFIsoValueGamma03PFIdPFIso_*_*',
    'keep *_elPFIsoValueNeutral03PFIdPFIso_*_*',
    'keep recoCaloJets_ak5CaloJets_*_*',
    'keep recoCaloMETs_met_*_*',
    'keep *_allConversions_*_*',
    'keep *_muPFIsoValue*_*_*',
    'keep *_elPFIsoValue*_*_*',
    'keep *_*provInfo*_*_*',
    'keep *_pfIsolated*_*_*',
    'keep *_pfNoElectron*_*_*',
    'keep *SuperCluster*_pfElectronTranslator_*_*',
    'keep *_correctedMulti5x5SuperClustersWithPreshower_*_*',
    'keep *_correctedHybridSuperClusters_*_*'
    ])
  from PhysicsTools.PatAlgos.patEventContent_cff import patTriggerStandAloneEventContent
  RA2PATOutput += patTriggerStandAloneEventContent
  return RA2PATOutput
